services:
  MySQL:
    image: mysql:latest
    container_name: MySQL
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
  Admin:
    image: phpmyadmin
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 6060:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  database: